# Generated by Django 5.2.3 on 2025-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('personal website', 'Personal Website'), ('resume', 'Resume'), ('other', 'Other'), ('github', 'GitHub')], max_length=20),
        ),
    ]
