# Generated by Django 5.2.3 on 2025-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('personal website', 'Personal Website'), ('resume', 'Resume'), ('github', 'GitHub')], max_length=20),
        ),
    ]
